name: CI/CD Pipeline

on:
  push:
    branches: [ mlops ]
  pull_request:
    branches: [ mlops ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Cache pip packages
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pip install pytest
        pytest

    - name: Train model
      run: python train.py

    - name: Deploy to PythonAnywhere
      if: github.event_name == 'push' && github.ref == 'refs/heads/mlops'
      env:
        PYTHONANYWHERE_API_TOKEN: ${{ secrets.PYTHONANYWHERE_TOKEN }}
        WORKON_HOME: ${{ runner.temp }}/virtualenvs
      run: |
        pip install pythonanywhere
        mkdir -p $WORKON_HOME
        pa_autoconfigure_django.py --python=3.8 https://github.com/${{ github.repository }}

    - name: Notify on success
      if: success()
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        text: Deployment to PythonAnywhere successful!
        webhook_url: ${{ secrets.SLACK_WEBHOOK }}

    - name: Notify on failure
      if: failure()
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        text: Deployment to PythonAnywhere failed. Check the logs for details.
        webhook_url: ${{ secrets.SLACK_WEBHOOK }}