name: CI/CD Pipeline

on:
  push:
    branches: [ mlops ]
  pull_request:
    branches: [ mlops ]

jobs:
  build-test-train-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Cache pip packages
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: List project structure
      run: |
        pwd
        ls -R

    - name: Run tests
      run: |
        pytest -v

    - name: Train model
      run: |
        python train.py

    - name: Upload trained model
      uses: actions/upload-artifact@v2
      with:
        name: trained-model
        path: house_price_model.joblib

    - name: Deploy to PythonAnywhere
      if: github.event_name == 'push' && github.ref == 'refs/heads/mlops'
      env:
        PYTHONANYWHERE_API_TOKEN: ${{ secrets.PYTHONANYWHERE_TOKEN }}
      run: |
        pip install pythonanywhere
        pa_autoconfigure_django.py --python=3.8 https://github.com/${{ github.repository }}

    - name: Notify on failure
      if: failure()
      run: |
        echo "The workflow has failed. Please check the logs for more information."
        # You can add more notification methods here, like sending an email or a chat message

    - name: Notify on success
      if: success()
      run: |
        echo "The workflow has completed successfully!"
        # You can add more notification methods here, like sending an email or a chat message