name: CI/CD Pipeline

on:
  push:
    branches: [ mlops ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Train model
      run: python train.py

    - name: Deploy to PythonAnywhere
      env:
        PA_TOKEN: ${{ secrets.PYTHONANYWHERE_TOKEN }}
        WORKON_HOME: ${{ runner.temp }}/virtualenvs
      run: |
        pip install pythonanywhere
        mkdir -p $WORKON_HOME
        export PYTHONANYWHERE_API_TOKEN=$PA_TOKEN
        pa_autoconfigure_django.py --python=3.8 https://github.com/${{ github.repository }}